/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20RulesSol from "./ERC20Rules.sol";
export { CompliantERC20__factory } from "./CompliantERC20__factory";
export { IdentityRegistry__factory } from "./IdentityRegistry__factory";
