/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Rules__factory } from "./ERC20Rules__factory";
export { ICompliantERC20__factory } from "./ICompliantERC20__factory";
