/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20RulesSol from "./ERC20Rules.sol";
export type { erc20RulesSol };
export type { CompliantERC20 } from "./CompliantERC20";
export type { IdentityRegistry } from "./IdentityRegistry";
