/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ActivityNFTFactoryInterface extends Interface {
  getFunction(nameOrSignature: "createActivityNFT"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ActivityNFTCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createActivityNFT",
    values: [string, AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createActivityNFT",
    data: BytesLike
  ): Result;
}

export namespace ActivityNFTCreatedEvent {
  export type InputTuple = [
    activityNFTAddress: AddressLike,
    blindAuctionAddress: AddressLike
  ];
  export type OutputTuple = [
    activityNFTAddress: string,
    blindAuctionAddress: string
  ];
  export interface OutputObject {
    activityNFTAddress: string;
    blindAuctionAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ActivityNFTFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ActivityNFTFactory;
  waitForDeployment(): Promise<this>;

  interface: ActivityNFTFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createActivityNFT: TypedContractMethod<
    [
      activityRight: string,
      encryptedERC20Address: AddressLike,
      biddingTime: BigNumberish,
      feeRecipient: AddressLike,
      feePercentageBp: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createActivityNFT"
  ): TypedContractMethod<
    [
      activityRight: string,
      encryptedERC20Address: AddressLike,
      biddingTime: BigNumberish,
      feeRecipient: AddressLike,
      feePercentageBp: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "ActivityNFTCreated"
  ): TypedContractEvent<
    ActivityNFTCreatedEvent.InputTuple,
    ActivityNFTCreatedEvent.OutputTuple,
    ActivityNFTCreatedEvent.OutputObject
  >;

  filters: {
    "ActivityNFTCreated(address,address)": TypedContractEvent<
      ActivityNFTCreatedEvent.InputTuple,
      ActivityNFTCreatedEvent.OutputTuple,
      ActivityNFTCreatedEvent.OutputObject
    >;
    ActivityNFTCreated: TypedContractEvent<
      ActivityNFTCreatedEvent.InputTuple,
      ActivityNFTCreatedEvent.OutputTuple,
      ActivityNFTCreatedEvent.OutputObject
    >;
  };
}
