import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBarComp } from "@/app/NavBarComp";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { WagmiProvider } from 'wagmi'
import { config } from '../lib/config'

const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient()


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <WagmiProvider config={config}>
          <QueryClientProvider client={queryClient}>
            <body className={inter.className}>
              <NavBarComp>{children}</NavBarComp>
            </body>
          </QueryClientProvider>
        </WagmiProvider>
    </html>

  );
}
