

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBarComp } from "@/app/NavBarComp";
import { Providers } from "./providers";
import { cookieToInitialState } from 'wagmi'
import { headers } from 'next/headers'
import { config, projectId} from '../lib/config'

import { initializeApp } from "firebase/app";



const inter = Inter({ subsets: ["latin"] });

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyAgWyENrwhXuxs-HGs48ge0ZK7q2KiHO54",
  authDomain: "betybed-7aa8d.firebaseapp.com",
  projectId: "betybed-7aa8d",
  storageBucket: "betybed-7aa8d.appspot.com",
  messagingSenderId: "514652504524",
  appId: "1:514652504524:web:1cc7d749203fb9faf99d69"
};

const app = initializeApp(firebaseConfig);


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))

  return (
    <>
        <html lang="en">
          <body className={inter.className}>
            <NavBarComp>

                <Providers initialState={initialState}>{children}</Providers>

            </NavBarComp>
          </body>
        </html>
      </>

  );
}
